apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: quay.io/brancz/prometheu s-example-app:v0.3.0
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app-svc
  labels:
    app: prometheus-example-app
spec:
  selector:
    app: prometheus-example-app
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: 8080